[tool.mypy]
mypy_path = "packages/sciresearch-core/src"
files = "packages/sciresearch-core/src/"
check_untyped_defs = true
disallow_any_unimported = false # This is too strict for now, as it will complain about untyped 3rd party libs
disallow_untyped_calls = false # This is also too strict for now
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.isort]
profile = "black"

[tool.ruff.lint]
ignore = ["E402", "F841", "F401", "F821"]
