"""Causal Audit Trail (CAT) toy example."""

from __future__ import annotations

from sciresearch_ai import __version__


def build_causal_audit_trail() -> dict[str, list[str] | str]:
    """Create a simple causal structure for a model answer."""
    trail: dict[str, list[str] | str] = {
        "claim": "Answer generated by LLM",
        "sources": ["document1.txt", "document2.txt"],
        "operations": ["retrieval", "generation"],
        "edges": [
            ("document1.txt", "retrieval"),
            ("document2.txt", "retrieval"),
            ("retrieval", "generation"),
        ],
    }
    return trail


def main() -> None:
    trail = build_causal_audit_trail()
    print("Causal audit trail:", trail)
    print("sciresearch_ai version:", __version__)


if __name__ == "__main__":
    main()
