name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yaml'
      - 'pyproject.toml'
      - 'importlinter.ini'
      - '.pre-commit-config.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yaml'
      - 'pyproject.toml'
      - 'importlinter.ini'
      - '.pre-commit-config.yaml'

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit import-linter
        pip install -e packages/sciresearch-core
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
    - name: Run import-linter
      run: |
        PYTHONPATH=.:packages/sciresearch-core/src lint-imports
    - name: Run mypy
      run: |
        mypy
